"""empty message

Revision ID: 16aa37874b60
Revises: 739611644452
Create Date: 2020-07-17 05:21:52.826815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16aa37874b60'
down_revision = '739611644452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('visits', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'visits')
    # ### end Alembic commands ###
