"""empty message

Revision ID: d8105f5b14eb
Revises: 
Create Date: 2020-05-19 17:23:41.874354

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8105f5b14eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('urls_short_url_idx', table_name='urls')
    op.drop_table('urls')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('login_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('login_ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('recover_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recover_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('recover_ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('urls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_url', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('long_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='urls_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='urls_pkey')
    )
    op.create_index('urls_short_url_idx', 'urls', ['short_url'], unique=True)
    # ### end Alembic commands ###
