"""empty message

Revision ID: db785a2f0e05
Revises: d8105f5b14eb
Create Date: 2020-05-19 17:26:15.965293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db785a2f0e05'
down_revision = 'd8105f5b14eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_address', sa.Unicode(length=255), nullable=False),
    sa.Column('first_name', sa.Unicode(length=255), nullable=False),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.Column('password', sa.Unicode(length=128), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('created_ip', postgresql.INET(), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('login_ip', postgresql.INET(), nullable=True),
    sa.Column('recover_key', sa.Integer(), nullable=True),
    sa.Column('recover_time', sa.DateTime(), nullable=True),
    sa.Column('recover_ip', postgresql.INET(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('short_url', sa.Unicode(length=15), nullable=False),
    sa.Column('long_url', sa.Unicode(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('urls_short_url_idx', 'urls', ['short_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('urls_short_url_idx', table_name='urls')
    op.drop_table('urls')
    op.drop_table('users')
    # ### end Alembic commands ###
