name: urlshortener

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10:8
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Postgresql setup
      run: |
        psql -U postgres -c 'CREATE DATABASE urlshortener_test;'
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv run py.test --cov=./ --cov-report xml
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
       # User defined upload name. Visible in Codecov UI
        name: url-shortener-cov
        # Path to coverage file to upload
        file: ./coverage.xml
        fail_ci_if_error: true
